name = "TuringTurchinRegularization"
uuid = "b37985ca-e484-4e36-b0d8-2025aca49ee8"
authors = ["Batmaev <vbbatmaev@gmail.com>"]
version = "0.1.0"

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
